### ISSUE TITLE
Style Guide adoption

### ISSUE THREAD

**Issue by jim-rosales** [MBJO/prj-rev-bwfs-dasmoto#5]
Consider researching a CSS style guide and adopting the rules it dictates. Following a style guide for writing CSS will make your code easier to read and make all your files look more professional. 

Take for example [Airbnbs style guide](https://github.com/airbnb/css). 

Some of the rules they specify are 

- Use soft tabs (2 spaces) for indentation
- Prefer dashes over camelCasing in class names.
- Underscores and PascalCasing are okay if you are using BEM (see OOCSS and BEM below).
- Do not use ID selectors
- When using multiple selectors in a rule declaration, give each selector its own line.
- Put a space before the opening brace { in rule declarations
- In properties, put a space after, but not before, the : character.
- Put closing braces } of rule declarations on a new line
- Put blank lines between rule declarations

For example in this section you should:
- put a space before the opening brace { in rule declarations 
- put a space after, but not before, the : character.
- When using multiple selectors in a rule declaration, give each selector its own line.

The result being:
```CSS 
#heading,
h1 {
  font-family: helvetica;
  font-size: 100px;
  font-weight: bold;
  color: khaki;
  background-image: url(https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg);
  text-align: center;
}
```

https://github.com/MBJO/prj-rev-bwfs-dasmoto/blob/c9b1908a14b16625591f28ec1e52730ad296472f/Dasmoto/resources/CSS/style.css#L1-L8
